version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production

  proxy:
    image: jc21/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    depends_on:
      - app